apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodedemo
  name: nodedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodedemo
    spec:
      containers:
      - image: ibrahimvis/demo-app:072d555b60e9923d432c2badacadea54e45fbedf
        name: nodedemo
        resources: {}
status: {}
