apiVersion: v1
kind: Service
metadata:
  name: node-svc
  labels:
    app: node-svc
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30007
  selector:
    app: nodedemo
